# -*- coding: utf-8 -*-
"""cvision2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15K6HbJrubKLPLFFe9abO3nv_8-uImjkq
"""

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
from skimage import io
from PIL import Image
import matplotlib.pylab as plt
 # Create a list to store the urls of the images
urls = ["http://s0.geograph.org.uk/photos/40/57/405725_b17937da.jpg"]
  # Read and display the image
  # loop over the image URLs, you could store several image urls in the list

for url in urls:
 image = io.imread(url)
 image_2 = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

 cv2_imshow(image_2)
 print('\n')

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
from skimage import io
from PIL import Image
import matplotlib.pylab as plt
 # Create a list to store the urls of the images
urls = ["http://s0.geograph.org.uk/photos/40/57/405725_b17937da.jpg"]
  # Read and display the image
  # loop over the image URLs, you could store several image urls in the list

for url in urls:
 image = io.imread(url)
 image_2 = cv.cvtColor(image, cv.COLOR_BGR2RGB)
 final_frame = cv.hconcat((image, image_2))
 cv2_imshow(final_frame)
 print('\n')

